name: 'setup-python-composite'
description: 'Sample code for a composite action that requires some version of Python'
runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@v2
    with:
      python-version: '3.x'

  - run: python --version
    shell: bash

  - uses: ./javascript-action